### ISSUE TITLE
Create the dependency packages for 2.12.4 before respin of xcat-dep package

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-dep#14]
Few things need to be prepared in GSA before we re-spin the xcat-dep for the 2.12.4 release 

1. Create ipmitool-xcat version 1.8.17-1 packages  **[ in Process by @chenglch ]**
```
# find ./ -name "ipmitool-xcat-1.8.17*" -print
./sles11/ppc64/ipmitool-xcat-1.8.17-0.ppc64.rpm
./sles11/x86_64/ipmitool-xcat-1.8.17-0.x86_64.rpm
./rh6/ppc64/ipmitool-xcat-1.8.17-0.ppc64.rpm
./rh6/x86_64/ipmitool-xcat-1.8.17-0.x86_64.rpm
./sles12/x86_64/ipmitool-xcat-1.8.17-0.x86_64.rpm
./sles12/ppc64le/ipmitool-xcat-1.8.17-0.ppc64le.rpm
./rh7/ppc64/ipmitool-xcat-1.8.17-0.ppc64.rpm
./rh7/x86_64/ipmitool-xcat-1.8.17-0.x86_64.rpm
./rh7/ppc64le/ipmitool-xcat-1.8.17-0.ppc64le.rpm
```

2. Bump xCAT requirement to 1.8.17-1  https://github.com/xcat2/xcat-core/pull/2101  This one required step 1 to be completed **[DONE , waiting for step 1]**

3. Rebuild xCAT-genesis-base for ppc64 - **[DONE by @zet809, in GSA]**

4. Build the ipmitool-xcat for Ubuntu  **[ Owner ? ]**
@zet809  Anything else?

**Comment by zet809** [comment]
@whowutwut Hi, victor, I think a little further more packages are needed:
1. the ipmitool-xcat deb package for ppc64 and amd64
2. xCAT-genesis-base-ppc64 is ready for both rpm and deb, the xcat-genesis-base-amd64 deb and xCAT-genesis-base-x86_64 rpm is also needed, and the links for genesis-base are also needed to be replaced.

**Comment by zet809** [comment]
@whowutwut I am sorry that the 2nd comment above is incorrect, we don't need to rebuild xcat-genesis-base-x86_64 to add rtc-opal.ko is a hardware clock driver for OpenPOWER server only.

**Comment by whowutwut** [comment]
@zet809  do we have an owner for the ipmitool-xcat debian build?  Is @chenglch  also going to build that one?

**Comment by zet809** [comment]
Yes, the ipmitool-xcat_1.8.17-0, ipmitool-xcat_1.8.15-3 ppc64el and amd64 deb package are all build and uploaded by @chenglch

**Comment by chenglch** [comment]
status: Currently, all the os environment(11 platform) is ready, ansible playbook can work on 10 platforms to build the package automatically, but some error happens when build packages on ppc64 sles11.4 environment.  I plan to build this specific package manually.

**Comment by whowutwut** [comment]
👍 Great!
