### ISSUE TITLE
elilo-xcat-3.14-5_all.deb missing elilo-x86.efi

### ISSUE THREAD

**Issue by sjjf** [xcat2/xcat-dep#42]
The elilo-xcat package in the 2.16 bionic apt repo (elilo-xcat-3.14-5_all.deb) doesn't contain the elilo-x86.efi file. Looking at the debian packaging config it's not clear why, but it's definitely missing.

The sha1sum in the repo Packages file (fe6be1663d76b1434d7e0d07ad71d9a0f3720b72) matches the package I've got installed, so I'm pretty sure it's an issue with the package build.

The previous version (available in the 2.15 repo) doesn't have this problem.

**Comment by cxhong** [comment]
@sjjf  Thank you so much to catch this.   I put new package in the devel tree
https://xcat.org/files/xcat/repos/apt/devel/xcat-dep/pool/main/e/elilo-xcat/elilo-xcat_3.14-5_all.deb
you can manually download this and run `apt install` command.

**Comment by sjjf** [comment]
Thanks. Fortunately I don't need the support for larger kernels at the moment, but the fixed package is definitely appreciated.

**Comment by sjjf** [comment]
Um, the updated file works fine in a local install, but installing from the repository fails - the metadata in the repository needs to be updated to match the changed file contents (apt is complaining about the size not matching). Maybe updating the package version to 3.14-6 would be the easiest fix.

**Comment by gurevichmark** [comment]
@sjjf How did you encounter this issue ? Did you just notice that `elilo-xcat-3.14-5_all.deb` was missing `elilo-x86.efi` ? Or was there some action/command that failed for you ?

**Comment by sjjf** [comment]
@gurevichmark I was bitten by xcat2/xcat-core#6817, and went looking for a workaround. The workaround I picked was chain booting via elilo (the fallback path that xnba uses for older kernel images), and that lead me to discover that the elilo executable was missing.

Before we upgraded to 2.16.1 in early November /all/ our EFI builds were using the elilo chain boot, and then after the upgrade none of them were, despite exactly the same kernel images being in use - we successfully built a number of nodes mid-October, and they all came up with the chain boot configuration, then last week we tried building more nodes and had them fail with the direct boot configuration. I couldn't find any 2.16.0 packages to see what the cause of this change was, but in the end I modified xnba.pm:has_efistub() to unconditionally return 0 to force setstate() to use the fallback chain boot config.

**Comment by sjjf** [comment]
@gurevichmark After upgrading to the latest snapshot I've been hit by this issue again, so it looks like the updated package still hasn't hit the repository? Any chance of getting this sorted properly?

**Comment by gurevichmark** [comment]
@sjjf 
Did you upgrade from online repository or from the download of `xcat-dep-ubuntu-202011301320.tar.bz2`
And is the issue that apt is complaining about the size not matching or that package doesn't contain the `elilo-x86.efi` file ?

**Comment by sjjf** [comment]
I upgraded from the online repository to the 2.16.1-snap202104121621 version. The elilo-xcat package appears to still be the 3.14-5 version which doesn't include the `elilo.x86.efi` file. The package doesn't have any /packaging/ errors - all the package metadata matches the package itself, it's just that the package is missing the `elilo.x86.efi` file (which is the whole point of the package, of course).

I suspect the best way to resolve this would be to create a new package version (3.14-6) which fixes the packaging issue - trying to replace the package file with an updated one of the same version is likely to lead to confusion.

**Comment by gurevichmark** [comment]
`elilo-xcat-3.14-6` RPM and DEB files are now available on xcat.org
